### ISSUE TITLE
Entity name

### ISSUE THREAD

**Issue by makadaw** [jksk/NLCoreData#11]
Hello,

What do you think about changing the name of the entity? Do not get it from class but get from static method? I looked at the code, need to change some common methods.

**Comment by jksk** [comment]
I'm not 100% sure what you mean. My basic reasoning with using the class to create entities was to avoid using a string which can be misspelled and not caught by the compiler.

If you have a better way, I'd love to see it. Feel free to create a pull request. Thanks for your interest!

**Comment by makadaw** [comment]
Yes, I understand you idea, but sometimes entity name and class name is different (old developer use suffix or something else in class names). 

As a solution can be added static method to NSManagedObject Category

``` objective-c
+ (NSSstring*)entityName
{
    return NSStringFromClass([self class]);
}
```

And developer can rewrite this method in own model.
But also this method bring problems to current API. For example NSFetchRequest category:

``` objective-c
+ (instancetype)fetchRequestWithEntity:(Class)entity
```

How you feel about such changes? I can make pull request

**Comment by jksk** [comment]
I understand what you mean now. It's a good feature. I added the method you suggested to the latest commit, I hope it works for you.

NSFetchRequest's fetchRequestWithEntity doesn't need to be changed, since it can just can call +entityName itself.

Thanks for the input!

**Comment by makadaw** [comment]
You're welcome. :)
Do not forget to update README file :)
