### ISSUE TITLE
-saveNestedAsynchronousWithCallback: called after each context save, not finish

### ISSUE THREAD

**Issue by itsthejb** [jksk/NLCoreData#12]
Hi,

Nice little library, but found an issue with `-saveNestedAsynchronousWithCallback:`; it seems to make sense that the callback should only be executed when the final parent context is reached, but in the current implementation the callback is executed after _each_ asynchronous save. This means the block will be executed twice for a simple background context, for example.

I'm fairly sure this isn't intended. Anyway, keep up the good work!

**Comment by jksk** [comment]
Nice catch, thanks!

**Comment by itsthejb** [comment]
No probs!
