### ISSUE TITLE
[NSManagedObject deleteWithRequest:context:] issue

### ISSUE THREAD

**Issue by miniak** [jksk/NLCoreData#14]
In [NSManagedObject deleteWithRequest:context:] you have

> > NSFetchRequest\* request = [NSFetchRequest fetchRequestWithEntity:[self class] >> context:context];
> > 
> > if (block)
> >  block(request);
> > 
> > [request setIncludesPropertyValues:NO];
> > [request setIncludesSubentities:NO];
> > 
> > ...

This order makes it impossible to override the includesSubentities property
in the request block. Therefore I think a better way would be to call the block after setting the properties.

BTW: [request setIncludesSubentities:NO] is also being called in [NSFetchRequest fetchRequestWithEntity:context:], which is being called on the first line.

**Comment by jksk** [comment]
Good catch.

The setIncludesSubentities: is redundant, since it's already set in the fetchRequestWithEntity:context:, so I can remove that outright, while the setIncludesPropertyValues: makes sense.
