### ISSUE TITLE
[NSFetchRequest fetchRequestWithEntity:context:] issue

### ISSUE THREAD

**Issue by miniak** [jksk/NLCoreData#15]
[NSFetchRequest fetchRequestWithEntity:context:] sets includesPropertyValues to NO, which is non default value. This makes the default fetching (and also counting and deleting) behavior unexpected.

I think that the right way is not to modify includesPropertyValues and let the user to set the property if he desires so. I know that I can switch it back to YES, but I have to use the block variants of the methods, which complicates my code unnecessarily.

If you are concerned about backwards compatibility, a global switch/property could be added to change this default behavior.

**Comment by jksk** [comment]
I assume you mean includesSubentities, but yes, I agree that it's less than perfect. (This library grew out of a private project where this setting made a lot of sense.)

I'll add a fix for this is the next update.
