### ISSUE TITLE
The podspec currently available through cocoapods breaks the project

### ISSUE THREAD

**Issue by cooksimo** [jksk/NLCoreData#2]
Using the following works:

``` ruby
s.prefix_header_contents = "#ifdef __OBJC__\n#import \"NLCoreData.h\"\n#endif"
```

Instead of:

``` ruby
s.prefix_header_contents = '#import "NLCoreData.h"'
```

Which is currently found in the cocoapods podspec.

Please update the podspec, thanks!

**Comment by kevinrenskers** [comment]
When is the podspec going to be updated anyway? The one in this repo is using a non-existing tag, the one on cocoapods is very old.

**Comment by jksk** [comment]
Sorry, that somehow fell by the wayside. If it breaks the project, feel free to remove it from cocoapods.

**Comment by kevinrenskers** [comment]
If you could please add a new tag "v0.3.0.1" to the repository then everything should work fine.

**Comment by jksk** [comment]
Should work now.
