### ISSUE TITLE
0.4.5 crashes a lot

### ISSUE THREAD

**Issue by kevinrenskers** [jksk/NLCoreData#8]
When updated to 0.4.5 (via CocoaPods) I get a lot of crashes related to saving a backgroundContext. 0.4.4 and before all worked fine.

**Comment by jksk** [comment]
Any sample code or steps to reproduce you could give me would be great.

**Comment by kevinrenskers** [comment]
Hmm that's not so easy.. basically, I delete all objects from my context (`[NSManagedObjectContext backgroundContext]`), then loop over my JSON file and create new objects (`insertInContext`). Then at the end of the loop I call `[context saveNested]`.

I'll try to create a small sample project.

**Comment by jksk** [comment]
Awesome, thanks!

**Comment by kevinrenskers** [comment]
https://github.com/kevinrenskers/NLCoreDataCrash

The sync code is in the appdelegate. It usually runs fine on the first launch, after that it often crashes. If it doesn't simply kill and start and try again.

**Comment by kevinrenskers** [comment]
I have the feeling it might be related to background saving and the use of NSFetchedResultsController. Not sure though.

**Comment by jksk** [comment]
I found the issue and pushed a new version.

Also, I can see a problem in your sample code. Whenever you use a context that runs on a private dispatch queue (like the backgroundContext and the storeContext), you should wrap the operations in a performBlock, like so: [context performBlock:^{ code here }];

I should really do a better job of documenting that, and certainly Apple could too.

Thanks a lot for the bug report!

**Comment by kevinrenskers** [comment]
Should `[context saveNested]` be called within the `performBlock` block as well?

**Comment by diogobalseiro** [comment]
Kevin, I've been using saveNested inside the block and I'm yet to encounter an a problem.

I would recommend creating a class function that receives blocks and takes care of the threading and saving automatically, something like this:

```
+ (void) performChanges:(void(^)(NSManagedObjectContext *someContext)) changesBlock 
    withCompletion:(void(^)(BOOL code))completionBlock {

    [UtilityDirector dispatchBlockToSomeBackgroundThread:^{

        NSManagedObjectContext *context = [NSManagedObjectContext backgroundContext];

        changesBlock(context);

        BOOL success = [context saveNested];

        if (completionBlock) completionBlock(success);
    }];
}
```

A thread and the respective block are created, they execute a block of code (such as editing or deleting managedObjects), then save and clean up. Better than always having to manually create theses steps every time and risking forgetting something.

**Comment by jksk** [comment]
@kevinrenskers Yeah, the saving should also be done in the block.

@ArkReversed Nice design. Just a small note though: I don't know what dispatchBlockToSomeBackgroundThread does, but if you use Core Data's built-in private concurrency queues (like with NLCoreData), the actual dispatch is done by the system. The implementation should use one of the NSManagedObjectContext instance methods, performBlock or performBlockAndWait. Like so:

<pre>
+ (void) performChanges:(void(^)(NSManagedObjectContext *someContext)) changesBlock 
    withCompletion:(void(^)(BOOL code))completionBlock {
    [context performBlock:^{
        changesBlock(context);
        BOOL success = [context saveNested];
        if (completionBlock) completionBlock(success);
    }];
}
</pre>

Also, you might want to dispatch the completionBlock to a known queue.

Like so:

<pre>
if (completionBlock)
    dispatch_async(dispatch_get_main_queue(), ^{
        completionBlock(success);
    });
</pre>

Just some general thoughts though, I don't know what your setup looks like.

**Comment by diogobalseiro** [comment]
@jksk I usually use dispatch_async to have more freedom regarding the queues and priorities of the thread. (though to be honest, I tend not to fiddle much with it)

Regarding the completionBlock, I like it better this way because the block will run in the background and I can easily nest more heavy operations.

Thanks for the input ;)

**Comment by jksk** [comment]
@ArkReversed If it works for you, great. I'd be worried about future breakage, since as far as I understand it, the operations might run on the wrong thread. Contexts are still thread-specific and dispatch_async doesn't guarantee which thread it runs on (unlike performBlock).
